
//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION mbr INT_VAR msd_block = 4 sd_block = 9 gsd_block = 18 sota_block = 30 st_lvl = 3 attack_delay = 0 globe_bypass = 1 breachy_remove = 1 breachy_dispel = 0 friendly_dispel = 0 breach_combat = 1 breach_spec = 1 breach_combi = 0 breach_noncomb = 0 BEGIN


//__________________________________________________________________________________
//__________________________________________________________________________________


// ***** need to add breach/spellshield sectypes if not already there

ADD_SECTYPE ~BREACH~ ~~

ADD_SECTYPE ~SPELLSHIELD~ ~~

// then:

COPY_EXISTING ~msectype.2da~ ~override~
  COUNT_2DA_ROWS 2 rows
  FOR (row = 1; row < rows; ++row) BEGIN
    READ_2DA_ENTRY row 0 2 sec_typ
    PATCH_IF (~%sec_typ%~ STRING_EQUAL_CASE ~breach~) BEGIN
      SET breach_sectype = (row - 1)
    END
    PATCH_IF (~%sec_typ%~ STRING_EQUAL_CASE ~spellshield~) BEGIN
      SET spellshield_sectype = (row - 1)
    END
    PATCH_IF (~%sec_typ%~ STRING_EQUAL_CASE ~k1#Dispel~) BEGIN
      SET k1_dispel_sectype = (row - 1)
    END
  END
IF_EXISTS BUT_ONLY


//__________________________________________________________________________________
//__________________________________________________________________________________


// set visual effects for various combat protections

/*
***** look out for items - e.g. some IR stuff casts fire shield, some stuff applies nondetection, etc.

zero out hardcoded animations - replace:
 - spturni2.bam
 - spmagglo.bam
 - spshield.bam.
*/
COPY ~%MOD_FOLDER%/data/bam-vvc/spmagglo.bam~ ~override~
COPY ~%MOD_FOLDER%/data/bam-vvc/spmagglo.vvc~ ~override~
COPY ~%MOD_FOLDER%/data/bam-vvc/spturni2.bam~ ~override~
COPY ~%MOD_FOLDER%/data/bam-vvc/spturni2.vvc~ ~override~
COPY ~%MOD_FOLDER%/data/bam-vvc/spshield.bam~ ~override~

/*
remove ioun stone animnations
 - copy helm18.itm
 - read name strref
 - read string from the strref
 - find any items with the same name strref or whose name matches the string
 - delete any 215 effects with timing 2
*/
ACTION_IF (FILE_EXISTS_IN_GAME ~helm18.itm~) BEGIN
  COPY_EXISTING ~helm18.itm~ ~override~
    READ_LONG 0x08 ioun_strref
    GET_STRREF %ioun_strref% ioun_string
  BUT_ONLY
  COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
    READ_LONG 0x08 this_strref
    GET_STRREF %this_strref% this_string
    PATCH_IF (%this_strref% = %ioun_strref%) OR (~%this_string%~ STRING_EQUAL_CASE ~%ioun_string%~) BEGIN
      LPF DELETE_EFFECT INT_VAR match_opcode = 215 match_timing = 2 END
    END
  BUT_ONLY
END 

// add mybulbgr vvc and bam (renamed) to PfNW

COPY ~%MOD_FOLDER%/data/bam-vvc/mybulbgr.bam~ ~override/dkbulbgr.bam~
COPY ~%MOD_FOLDER%/data/bam-vvc/mybulbgr.vvc~ ~override/dkbulbgr.vvc~
  WRITE_ASCII 0x08 ~dkbulbgr~ #8

COPY_EXISTING ~spwi511.spl~ ~override~
  READ_LONG 0x08 spl_name
//  LPF DELETE_EFFECT INT_VAR match_opcode = 215 END // maybe not? this seems to be a one-time visual
  LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 120 opcode = 215 parameter1 = 0 parameter2 = 1 resist_dispel = 3 STR_VAR resource = ~dkbulbgr~ END
IF_EXISTS BUT_ONLY

/* 
// find all spells w/ same namne?
// ...but that will find ones that cast the original via 146... don't want to patch them
COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
  READ_LONG 0x08 this_name
  PATCH_IF (%this_name% = %spl_name%) BEGIN
  END
BUT_ONLY
*/

// add spcomett vvc and bam (renamed) to PfMW

COPY ~%MOD_FOLDER%/data/bam-vvc/spcomett.bam~ ~override/dkcomett.bam~
COPY ~%MOD_FOLDER%/data/bam-vvc/spcomett.vvc~ ~override/dkcomett.vvc~
  WRITE_ASCII 0x08 ~dkcomett~ #8

COPY_EXISTING ~spwi611.spl~ ~override~
  READ_LONG 0x08 spl_name
//  LPF DELETE_EFFECT INT_VAR match_opcode = 215 END // maybe not? this seems to be a one-time visual
  LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 142 opcode = 215 parameter1 = 0 parameter2 = 1 resist_dispel = 3 STR_VAR resource = ~dkcomett~ END
IF_EXISTS BUT_ONLY

// add modified dvmantle to prismatic mantle (unless SDRT)

// condition this on SR being present
ACTION_IF !(MOD_IS_INSTALLED ~d5_random_tweaks.tp2~ ~2708~) BEGIN
  COPY ~%MOD_FOLDER%/data/bam-vvc/dvmantle.bam~ ~override~
  COPY ~%MOD_FOLDER%/data/bam-vvc/dvmantle.vvc~ ~override~
END

/* no need
  COPY_EXISTING ~spwi708.spl~ ~override~
    LPF DELETE_EFFECT INT_VAR match_opcode = 215 END // maybe not? this seems to be a one-time visual
    LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 120 opcode = 215 parameter1 = 0 parameter2 = 1 resist_dispel = 3 STR_VAR resource = ~dkcomett~ END
  BUT_ONLY
END
*/

// add myimpman vvc and bam (renamed) to moment of prescience and delete existing 215 effect

ACTION_IF (FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~) BEGIN
  COPY ~%MOD_FOLDER%/data/bam-vvc/myimpman.bam~ ~override/dkimpman.bam~
  COPY ~%MOD_FOLDER%/data/bam-vvc/myimpman.vvc~ ~override/dkimpman.vvc~
    WRITE_ASCII 0x08 ~dkimpman~ #8
  COPY_EXISTING ~spwi808.spl~ ~override~
//    LPF DELETE_EFFECT INT_VAR match_opcode = 215 END // maybe not? this seems to be a one-time visual
    LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 142 opcode = 215 parameter1 = 0 parameter2 = 1 resist_dispel = 0 STR_VAR resource = ~dkimpman~ END 
  IF_EXISTS BUT_ONLY
END

// add spabsimm vvc and bam (renamed) to absolute immunity

COPY ~%MOD_FOLDER%/data/bam-vvc/spabsimm.bam~ ~override/dkabsimm.bam~
COPY ~%MOD_FOLDER%/data/bam-vvc/spabsimm.vvc~ ~override/dkabsimm.vvc~
  WRITE_ASCII 0x08 ~dkabsimm~ #8

COPY_EXISTING ~spwi907.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 142 opcode = 215 parameter1 = 0 parameter2 = 1 resist_dispel = 3 STR_VAR resource = ~dkabsimm~ END
IF_EXISTS BUT_ONLY

// add ion1red & ion2red vvc and bam (renamed) to Pro Missiles

COPY ~%MOD_FOLDER%/data/bam-vvc/ion1red.bam~ ~override/dkun1red.bam~
COPY ~%MOD_FOLDER%/data/bam-vvc/ion1red.vvc~ ~override/dkun1red.vvc~
  WRITE_ASCII 0x08 ~dkun1red~ #8
COPY ~%MOD_FOLDER%/data/bam-vvc/ion2red.bam~ ~override/dkun2red.bam~
COPY ~%MOD_FOLDER%/data/bam-vvc/ion2red.vvc~ ~override/dkun2red.vvc~
  WRITE_ASCII 0x08 ~dkun2red~ #8

COPY_EXISTING ~spwi311.spl~ ~override~
  LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 83 opcode = 215 parameter1 = 0 parameter2 = 1 resist_dispel = 3 STR_VAR resource = ~dkun1red~ END
  LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 83 opcode = 215 parameter1 = 0 parameter2 = 1 resist_dispel = 3 STR_VAR resource = ~dkun2red~ END
  LPF DELETE_EFFECT INT_VAR match_opcode = 156 END
IF_EXISTS BUT_ONLY

// add ion1blck & ion2blck vvc and bam (renamed) to Nondetection
// ...and set its sectype as a... specific protection

COPY ~%MOD_FOLDER%/data/bam-vvc/ion1blck.bam~ ~override/dkun1blk.bam~
COPY ~%MOD_FOLDER%/data/bam-vvc/ion1blck.vvc~ ~override/dkun1blk.vvc~
  WRITE_ASCII 0x08 ~dkun1blk~ #8
COPY ~%MOD_FOLDER%/data/bam-vvc/ion2blck.bam~ ~override/dkun2blk.bam~
COPY ~%MOD_FOLDER%/data/bam-vvc/ion2blck.vvc~ ~override/dkun2blk.vvc~
  WRITE_ASCII 0x08 ~dkun2blk~ #8

COPY_EXISTING ~spwi310.spl~ ~override~
			  ~spwi592.spl~ ~override~
			  ~dwsw310.spl~ ~override~
			  ~dwsw592.spl~ ~override~
  SAY UNIDENTIFIED_DESC @12310
  WRITE_BYTE 0x27 2
  LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 142 opcode = 215 parameter1 = 0 parameter2 = 1 resist_dispel = 3 STR_VAR resource = ~dkun1blk~ END
  LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 142 opcode = 215 parameter1 = 0 parameter2 = 1 resist_dispel = 3 STR_VAR resource = ~dkun2blk~ END
  LPF DELETE_EFFECT INT_VAR match_opcode = 156 END
IF_EXISTS BUT_ONLY


//__________________________________________________________________________________
//__________________________________________________________________________________


// next, modify spell protections


COPY_EXISTING ~kit.ids~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (row = 1; row < rows; ++row) BEGIN
    READ_2DA_ENTRY_FORMER rows row 0 ~code~
    READ_2DA_ENTRY_FORMER rows row 1 ~kit~
    PATCH_IF (~%kit%~ STRING_EQUAL_CASE ~MAGESCHOOL_ABJURER~) BEGIN
      SET abjurer_kit_code = %code%
    END
    PATCH_IF (~%kit%~ STRING_EQUAL_CASE ~D5_CM_MYSTRA~) BEGIN
      SET mystra_cm_code = %code%
    END
  END  
BUT_ONLY

COPY_EXISTING ~splstate.ids~ ~override~
  COUNT_2DA_ROWS 2 rows
  FOR (row = 1; row < rows; ++row) BEGIN
    READ_2DA_ENTRY row 0 2 spl_state
    PATCH_IF (~%spl_state%~ STRING_EQUAL_CASE ~BUFF_PRO_SPELLS~) BEGIN
      SET buff_pro_spells_row = row
    END
    PATCH_IF (~%spl_state%~ STRING_EQUAL_CASE ~PRO_SPELLS_LEVEL_FIVE_MINUS~) BEGIN
      SET pro_level_five_minus_row = row
    END
    PATCH_IF (~%spl_state%~ STRING_EQUAL_CASE ~PRO_SPELLS_LEVEL_SIX_SEVEN_EIGHT~) BEGIN
      SET pro_level_six_eight_row = row
    END
    PATCH_IF (~%spl_state%~ STRING_EQUAL_CASE ~SPELL_PROTECTION~) BEGIN
      SET spell_protection_row = row
    END
  END
IF_EXISTS BUT_ONLY

// add swirlw vvc and bam (renamed) to MSD (white)

COPY ~%MOD_FOLDER%/data/bam-vvc/swirlw.bam~ ~override/dkswrlw.bam~
COPY ~%MOD_FOLDER%/data/bam-vvc/swirlw.vvc~ ~override/dkswrlw.vvc~
  WRITE_ASCII 0x08 ~dkswrlw~ #8

ACTION_FOR_EACH msd_spl IN ~spwi318~ ~spra302~ ~d5_radfl~ ~dwsw318~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%msd_spl%.spl~) BEGIN
    COPY ~%MOD_FOLDER%/data/spl/%msd_spl%.spl~ ~override~
      SAY NAME1 @123181
      SAY UNIDENTIFIED_DESC @12318
      READ_SHORT 0x1c spl_typ
      READ_LONG 0x34 spl_lvl
      WRITE_ASCII 0x3a ~SPWI318C~ #8
      LPF ALTER_SPELL_HEADER STR_VAR icon = ~SPWI318B~ END
      LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 201 parameter1 = %msd_block% END
      PATCH_IF (VARIABLE_IS_SET %pro_level_five_minus_row%) BEGIN
        LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 328 match_parameter2 = %buff_pro_spells_row% parameter2 = %pro_level_five_minus_row% END
      END
      PATCH_IF (VARIABLE_IS_SET %spell_protection_row%) BEGIN
        LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 328 match_parameter2 = %buff_pro_spells_row% parameter2 = %spell_protection_row% END
      END
      PATCH_IF (FILE_EXISTS_IN_GAME ~d5__psionics.d5~) BEGIN
        PATCH_IF (spl_typ = 1) BEGIN
          LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5psaura~ END
        END
      END
      PATCH_IF (FILE_EXISTS_IN_GAME ~d5cmmys.2da~) AND (VARIABLE_IS_SET %mystra_cm_code%) AND (FILE_EXISTS_IN_GAME ~d5_abju.eff~) BEGIN
        LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = %mystra_cm_code% parameter2 = 9 resist_dispel = 0 timing = 9 power = 0 STR_VAR resource = ~d5_abju~ END
      END
      PATCH_IF (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~40~) AND (VARIABLE_IS_SET %abjurer_kit_code%) AND (FILE_EXISTS_IN_GAME ~d5_abju.eff~) BEGIN
        LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = %abjurer_kit_code% parameter2 = 9 resist_dispel = 0 timing = 9 power = 0 STR_VAR resource = ~d5_abju~ END
      END
	  PATCH_IF (MOD_IS_INSTALLED ~stratagems.tp2~ ~6000~) BEGIN	// or (FILE_EXISTS_IN_GAME ~DW#BLHDA.spl~)
	    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = ~DW#HDANI~ END
	    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 146 target = 1 parameter1 = 1 parameter2 = 1 timing = 0 STR_VAR resource = ~DW#BLHDA~ END
	  END
/* already added manually in 318b
    COPY_EXISTING ~spwi318b.spl~ ~override~
      LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 321 STR_VAR resource = ~%msd_spl%~ END
    IF_EXISTS BUT_ONLY
*/
  END
END
ACTION_FOR_EACH extra_msd_spl IN ~d5p2318~ ~d5f2318~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%extra_msd_spl%.spl~) BEGIN
    COPY ~%MOD_FOLDER%/data/spl/%extra_msd_spl%.spl~ ~override~
      SAY NAME1 @123181
      SAY UNIDENTIFIED_DESC @12318
      WRITE_ASCII 0x3a ~SPWI318C~ #8
      LPF ALTER_SPELL_HEADER STR_VAR icon = ~SPWI318B~ END
  END
END

// add swirlb vvc and bam (renamed) to SD (blue)

COPY ~%MOD_FOLDER%/data/bam-vvc/swirlb.bam~ ~override/dkswrlb.bam~
COPY ~%MOD_FOLDER%/data/bam-vvc/swirlb.vvc~ ~override/dkswrlb.vvc~
  WRITE_ASCII 0x08 ~dkswrlb~ #8

ACTION_FOR_EACH sd_spl IN ~spwi522~ ~spwi618~ ~dwsw522~ ~dwsw618~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%sd_spl%.spl~) BEGIN
    COPY ~%MOD_FOLDER%/data/spl/%sd_spl%.spl~ ~override~
      SAY NAME1 @125221
      SAY UNIDENTIFIED_DESC @12522
      READ_SHORT 0x1c spl_typ
      READ_LONG 0x34 spl_lvl
      WRITE_ASCII 0x3a ~SPWI618C~ #8
      LPF ALTER_SPELL_HEADER STR_VAR icon = ~SPWI618B~ END
      LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 201 parameter1 = %sd_block% END
      PATCH_IF (VARIABLE_IS_SET %pro_level_five_minus_row%) BEGIN
        LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 328 match_parameter2 = %buff_pro_spells_row% parameter2 = %pro_level_five_minus_row% END
      END
      PATCH_IF (VARIABLE_IS_SET %pro_level_six_eight_row%) BEGIN
        LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 328 match_parameter2 = %buff_pro_spells_row% parameter2 = %pro_level_six_eight_row% END
      END
      PATCH_IF (VARIABLE_IS_SET %spell_protection_row%) BEGIN
        LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 328 match_parameter2 = %buff_pro_spells_row% parameter2 = %spell_protection_row% END
      END
      PATCH_IF (FILE_EXISTS_IN_GAME ~d5__psionics.d5~) BEGIN
        PATCH_IF (spl_typ = 1) BEGIN
          LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5psaura~ END
        END
      END
      PATCH_IF (FILE_EXISTS_IN_GAME ~d5cmmys.2da~) AND (VARIABLE_IS_SET %mystra_cm_code%) AND (FILE_EXISTS_IN_GAME ~d5_abju.eff~) BEGIN
        LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = %mystra_cm_code% parameter2 = 9 resist_dispel = 0 timing = 9 power = 0 STR_VAR resource = ~d5_abju~ END
      END
      PATCH_IF (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~40~) AND (VARIABLE_IS_SET %abjurer_kit_code%) AND (FILE_EXISTS_IN_GAME ~d5_abju.eff~) BEGIN
        LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = %abjurer_kit_code% parameter2 = 9 resist_dispel = 0 timing = 9 power = 0 STR_VAR resource = ~d5_abju~ END
      END
	  PATCH_IF (MOD_IS_INSTALLED ~stratagems.tp2~ ~6000~) BEGIN	// or (FILE_EXISTS_IN_GAME ~DW#BLHDA.spl~)
	    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = ~DW#HDANI~ END
	    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 146 target = 1 parameter1 = 1 parameter2 = 1 timing = 0 STR_VAR resource = ~DW#BLHDA~ END
	  END
/* already added manually in 522b
    COPY_EXISTING ~spwi522b.spl~ ~override~
      LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 321 STR_VAR resource = ~%msd_spl%~ END
    IF_EXISTS BUT_ONLY
*/
  END
END
ACTION_FOR_EACH extra_sd_spl IN ~d5p2522~ ~d5f2522~ ~d5p2618~ ~d5f2618~ ~spin710~ ~amul25~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%extra_sd_spl%.spl~) BEGIN
    COPY ~%MOD_FOLDER%/data/spl/%extra_sd_spl%.spl~ ~override~
      SAY NAME1 @125221
      SAY UNIDENTIFIED_DESC @12522
      WRITE_ASCII 0x3a ~SPWI618C~ #8
      LPF ALTER_SPELL_HEADER STR_VAR icon = ~SPWI618B~ END
  END
END

// add swirly vvc and bam (renamed) to GSD (yellow)

COPY ~%MOD_FOLDER%/data/bam-vvc/swirly.bam~ ~override/dkswrly.bam~
COPY ~%MOD_FOLDER%/data/bam-vvc/swirly.vvc~ ~override/dkswrly.vvc~
  WRITE_ASCII 0x08 ~dkswrly~ #8

ACTION_FOR_EACH gsd_spl IN ~spwi701~ ~dw#mlstn~ ~dwsw701~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%gsd_spl%.spl~) BEGIN
    COPY ~%MOD_FOLDER%/data/spl/%gsd_spl%.spl~ ~override~
      SAY NAME1 @127011
      SAY UNIDENTIFIED_DESC @12701
      READ_SHORT 0x1c spl_typ
      READ_LONG 0x34 spl_lvl
      READ_LONG 0x34 spl_lvl
      WRITE_ASCII 0x3a ~SPWI522C~ #8
      LPF ALTER_SPELL_HEADER STR_VAR icon = ~SPWI522B~ END
      LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 201 parameter1 = %gsd_block% END
      PATCH_IF (VARIABLE_IS_SET %pro_level_six_eight_row%) BEGIN
        LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 328 match_parameter2 = %buff_pro_spells_row% parameter2 = %pro_level_six_eight_row% END
      END
      PATCH_IF (VARIABLE_IS_SET %spell_protection_row%) BEGIN
        LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 328 match_parameter2 = %buff_pro_spells_row% parameter2 = %spell_protection_row% END
      END
      PATCH_IF (FILE_EXISTS_IN_GAME ~d5__psionics.d5~) BEGIN
        PATCH_IF (spl_typ = 1) BEGIN
          LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5psaura~ END
        END
      END
      PATCH_IF (FILE_EXISTS_IN_GAME ~d5cmmys.2da~) AND (VARIABLE_IS_SET %mystra_cm_code%) AND (FILE_EXISTS_IN_GAME ~d5_abju.eff~) BEGIN
        LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = %mystra_cm_code% parameter2 = 9 resist_dispel = 0 timing = 9 power = 0 STR_VAR resource = ~d5_abju~ END
      END
      PATCH_IF (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~40~) AND (VARIABLE_IS_SET %abjurer_kit_code%) AND (FILE_EXISTS_IN_GAME ~d5_abju.eff~) BEGIN
        LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = %abjurer_kit_code% parameter2 = 9 resist_dispel = 0 timing = 9 power = 0 STR_VAR resource = ~d5_abju~ END
      END
	  PATCH_IF (MOD_IS_INSTALLED ~stratagems.tp2~ ~6000~) BEGIN	// or (FILE_EXISTS_IN_GAME ~DW#BLHDA.spl~)
	    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = ~DW#HDANI~ END
	    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 146 target = 1 parameter1 = 1 parameter2 = 1 timing = 0 STR_VAR resource = ~DW#BLHDA~ END
	  END
/* already added manually to 701b
    COPY_EXISTING ~spwi701b.spl~ ~override~
      LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 321 STR_VAR resource = ~%msd_spl%~ END
    IF_EXISTS BUT_ONLY
*/
  END
END
ACTION_FOR_EACH extra_gsd_spl IN ~d5p2701~ ~d5f2701~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%extra_gsd_spl%.spl~) BEGIN
    COPY ~%MOD_FOLDER%/data/spl/%extra_gsd_spl%.spl~ ~override~
      SAY NAME1 @127011
      SAY UNIDENTIFIED_DESC @12701
      WRITE_ASCII 0x3a ~SPWI522C~ #8
      LPF ALTER_SPELL_HEADER STR_VAR icon = ~SPWI522B~ END
  END
END

// add swirlp vvc and bam (renamed) to Spell Trap (purple)

COPY ~%MOD_FOLDER%/data/bam-vvc/swirlp.bam~ ~override/dkswrlp.bam~
COPY ~%MOD_FOLDER%/data/bam-vvc/swirlp.vvc~ ~override/dkswrlp.vvc~
  WRITE_ASCII 0x08 ~dkswrlp~ #8

ACTION_FOR_EACH trap_spl IN ~spwi902~ ~dwsw902~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%trap_spl%.spl~) BEGIN
    COPY ~%MOD_FOLDER%/data/spl/%trap_spl%.spl~ ~override~
      SAY NAME1 @129021
      SAY UNIDENTIFIED_DESC @12902
      READ_SHORT 0x1c spl_typ
      READ_LONG 0x34 spl_lvl
      PATCH_IF (VARIABLE_IS_SET %spell_protection_row%) BEGIN
        LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 328 match_parameter2 = %buff_pro_spells_row% parameter2 = %spell_protection_row% END
      END
      PATCH_IF (FILE_EXISTS_IN_GAME ~d5__psionics.d5~) BEGIN
        PATCH_IF (spl_typ = 1) BEGIN
          LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5psaura~ END
        END
      END
      PATCH_IF (FILE_EXISTS_IN_GAME ~d5cmmys.2da~) AND (VARIABLE_IS_SET %mystra_cm_code%) AND (FILE_EXISTS_IN_GAME ~d5_abju.eff~) BEGIN
        LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = %mystra_cm_code% parameter2 = 9 resist_dispel = 0 timing = 9 power = 0 STR_VAR resource = ~d5_abju~ END
      END
      PATCH_IF (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~40~) AND (VARIABLE_IS_SET %abjurer_kit_code%) AND (FILE_EXISTS_IN_GAME ~d5_abju.eff~) BEGIN
        LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = %abjurer_kit_code% parameter2 = 9 resist_dispel = 0 timing = 9 power = 0 STR_VAR resource = ~d5_abju~ END
      END
	  PATCH_IF (MOD_IS_INSTALLED ~stratagems.tp2~ ~6000~) BEGIN	// or (FILE_EXISTS_IN_GAME ~DW#BLHDA.spl~)
	    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = ~DW#HDANI~ END
	    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 146 target = 1 parameter1 = 1 parameter2 = 1 timing = 0 STR_VAR resource = ~DW#BLHDA~ END
	  END
// ***** need to block breach?
  END
END
ACTION_FOR_EACH extra_trap_spl IN ~d5p2902~ ~d5f2902~ ~staf11~ ~staf11b~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%extra_trap_spl%.spl~) BEGIN
    COPY ~%MOD_FOLDER%/data/spl/%extra_trap_spl%.spl~ ~override~
      SAY NAME1 @129021
      SAY UNIDENTIFIED_DESC @12902
  END
END

// add swirlt vvc and bam (renamed) to Shield of the Archons (teal?)

COPY ~%MOD_FOLDER%/data/bam-vvc/swirlt.bam~ ~override/dkswrlt.bam~
COPY ~%MOD_FOLDER%/data/bam-vvc/swirlt.vvc~ ~override/dkswrlt.vvc~
  WRITE_ASCII 0x08 ~dkswrlt~ #8

ACTION_FOR_EACH sota_spl IN ~sppr701~ ~qdfv_701~ ~dgarchon~ ~dwsp701~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%sota_spl%.spl~) BEGIN
    COPY ~%MOD_FOLDER%/data/spl/%sd_spl%.spl~ ~override~
      SAY NAME1 @117011
      SAY UNIDENTIFIED_DESC @11701
      READ_SHORT 0x1c spl_typ
      READ_LONG 0x34 spl_lvl
      LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 201 parameter1 = %sota_block% END
      PATCH_IF (FILE_EXISTS_IN_GAME ~d5cmmys.2da~) AND (VARIABLE_IS_SET %mystra_cm_code%) AND (FILE_EXISTS_IN_GAME ~d5_abju.eff~) BEGIN
        LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = %mystra_cm_code% parameter2 = 9 resist_dispel = 0 timing = 9 power = 0 STR_VAR resource = ~d5_abju~ END
      END
      PATCH_IF (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~40~) AND (VARIABLE_IS_SET %abjurer_kit_code%) AND (FILE_EXISTS_IN_GAME ~d5_abju.eff~) BEGIN
        LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = %abjurer_kit_code% parameter2 = 9 resist_dispel = 0 timing = 9 power = 0 STR_VAR resource = ~d5_abju~ END
      END
/* already added manually to 701b... I think...
    COPY_EXISTING ~sppr701b.spl~ ~override~
      LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 321 STR_VAR resource = ~%msd_spl%~ END
    IF_EXISTS BUT_ONLY
*/
  END
END


// MGOI

COPY_EXISTING ~spwi406.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR resist_dispel = 2 END
  PATCH_IF (globe_bypass = 0) BEGIN
    LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 102 opcode = 206 parameter1 = 0 STR_VAR resource = ~d5dispel~ END
    LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 102 opcode = 206 parameter1 = 0 STR_VAR resource = ~d5disrem~ END
    PATCH_IF (FILE_EXISTS_IN_GAME ~a^dispe2.spl~) BEGIN
      LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 102 opcode = 206 parameter1 = 0 STR_VAR resource = ~a^dispe2~ END
    END
  END
BUT_ONLY


// GOI

COPY_EXISTING ~spwi602.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR resist_dispel = 2 END
  PATCH_IF (globe_bypass = 0) BEGIN
    LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 102 opcode = 206 parameter1 = 0 STR_VAR resource = ~d5dispel~ END
    LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 102 opcode = 206 parameter1 = 0 STR_VAR resource = ~d5disrem~ END
    PATCH_IF (FILE_EXISTS_IN_GAME ~a^dispe2.spl~) BEGIN
      LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 102 opcode = 206 parameter1 = 0 STR_VAR resource = ~a^dispe2~ END
    END
  END  
BUT_ONLY


// spell shield

COPY ~%MOD_FOLDER%/data/bam-vvc/mybluorb.bam~ ~override/dkbluorb.bam~
COPY ~%MOD_FOLDER%/data/bam-vvc/mybluorb.vvc~ ~override/dkbluorb.vvc~
  WRITE_ASCII 0x08 ~dkbluorb~ #8

ACTION_FOR_EACH ss_spl IN ~spwi519~ ~dwsw519~ ~dw#isss~ ~zpwi519~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%ss_spl%.spl~) BEGIN
    COPY ~%MOD_FOLDER%/data/spl/%ss_spl%.spl~ ~override~
      SAY NAME1 @125191
      SAY UNIDENTIFIED_DESC @12519
      WRITE_ASCII 0x3a ~SPWI801C~ #8
      LPF ALTER_SPELL_HEADER STR_VAR icon = ~SPWI801B~ END
      PATCH_IF (VARIABLE_IS_SET %spellshield_sectype%) BEGIN
	    WRITE_BYTE 0x27 %spellshield_sectype%
	  END
      PATCH_IF !(FILE_EXISTS_IN_GAME ~dw#w519a.spl~) BEGIN
        LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 142 opcode = 215 parameter1 = 0 parameter2 = 1 resist_dispel = 0 STR_VAR resource = ~dkbluorb~ END
      END
      PATCH_IF (FILE_EXISTS_IN_GAME ~dw#w519b.spl~) BEGIN
        LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 206 STR_VAR resource = ~dw#w519b~ END
      END
      PATCH_IF (FILE_EXISTS_IN_GAME ~dw#w519a.eff~) BEGIN
        LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 206 opcode = 272 parameter1 = 1 parameter2 = 3 STR_VAR resource = ~dw#w519a~ END
      END
      PATCH_IF (FILE_EXISTS_IN_GAME ~d5__psionics.d5~) BEGIN
        PATCH_IF (spl_typ = 1) BEGIN
          LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5psaura~ END
        END
      END
  END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~dw#w519a.spl~) BEGIN
  COPY_EXISTING ~dw#w519a.spl~ ~override~
    LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 206 opcode = 215 parameter1 = 0 parameter2 = 1 resist_dispel = 0 STR_VAR resource = ~dkbluorb~ END
  BUT_ONLY
  COPY_EXISTING ~zpwi519.spl~ ~override~
    LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 142 opcode = 215 parameter1 = 0 parameter2 = 1 resist_dispel = 0 STR_VAR resource = ~dkbluorb~ END
  IF_EXISTS BUT_ONLY
END

// set beholders' antimagic ray to interact properly with spell shield
// ...should probably actually make them interact with dispelling screen, not spell shield...
// experimentally: how about both?  :)

COPY ~%MOD_FOLDER%/data/spl/spin550.spl~ ~override~
  SAY NAME1 @14550

COPY ~%MOD_FOLDER%/data/spl/spin550b.spl~ ~override~

COPY ~%MOD_FOLDER%/data/spl/spin550c.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 221 parameter2 = %spellshield_sectype% END
  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 parameter2 = %spellshield_sectype% END

COPY ~%MOD_FOLDER%/data/spl/spin992.spl~ ~override~
  SAY NAME1 @14992

COPY ~%MOD_FOLDER%/data/spl/spin992b.spl~ ~override~

COPY ~%MOD_FOLDER%/data/spl/spin992c.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 221 parameter2 = %spellshield_sectype% END
  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 parameter2 = %spellshield_sectype% END

ACTION_IF (FILE_EXISTS_IN_GAME ~k1#scre.spl~) BEGIN
  COPY_EXISTING ~k1#scre.spl~ ~override~
    LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 206 STR_VAR match_resource = ~spwi513b~ resource = ~spin550b~ END
    LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 206 STR_VAR match_resource = ~spwi513b~ resource = ~spin992b~ END
  COPY_EXISTING ~spin550.spl~ ~override~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter2 = 1 timing = 1 STR_VAR resource = ~spin550d~ END
  COPY ~%MOD_FOLDER%/data/spl/spin550c.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 221 parameter2 = %k1_dispel_sectype% END
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 parameter2 = %k1_dispel_sectype% END
  COPY ~%MOD_FOLDER%/data/spl/spin550d.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 221 parameter2 = %spellshield_sectype% END
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 parameter2 = %spellshield_sectype% END
  COPY_EXISTING ~spin992.spl~ ~override~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter2 = 1 timing = 1 STR_VAR resource = ~spin992d~ END
  COPY ~%MOD_FOLDER%/data/spl/spin992c.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 221 parameter2 = %k1_dispel_sectype% END
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 parameter2 = %k1_dispel_sectype% END
  COPY ~%MOD_FOLDER%/data/spl/spin992d.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 221 parameter2 = %spellshield_sectype% END
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 parameter2 = %spellshield_sectype% END
END
  

//__________________________________________________________________________________
//__________________________________________________________________________________


// next, magic attacks


// spell thrust

COPY ~%MOD_FOLDER%/data/spl/spwi321.spl~ ~override~
  SAY NAME1 @123211
  SAY UNIDENTIFIED_DESC @12321
  READ_SHORT 0x1c spl_typ
  PATCH_IF (FILE_EXISTS_IN_GAME ~d5__psionics.d5~) BEGIN
    PATCH_IF (spl_typ = 1) BEGIN
      LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5psaura~ END
    END
  END
  PATCH_IF (MOD_IS_INSTALLED ~stratagems.tp2~ ~6000~) BEGIN	// or (FILE_EXISTS_IN_GAME ~DW#BLHDA.spl~)
    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = ~DW#HDANI~ END
    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 146 target = 1 parameter1 = 1 parameter2 = 1 timing = 0 STR_VAR resource = ~DW#BLHDA~ END
  END

ACTION_IF (FILE_EXISTS_IN_GAME ~d5p2321.spl~) BEGIN
  COPY_EXISTING ~d5p2321.spl~ ~override~
    READ_LONG 0x34 lvl
  BUT_ONLY
  COPY ~%MOD_FOLDER%/data/spl/d5p2321.spl~ ~override~
    WRITE_SHORT 0x1c 2
    WRITE_LONG 0x34 lvl
END
  
COPY ~%MOD_FOLDER%/data/spl/spwi321b.spl~ ~override~
  PATCH_IF (attack_delay > 0) BEGIN
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 timing = 4 duration = %attack_delay% END
  END

COPY ~%MOD_FOLDER%/data/spl/spwi321c.spl~ ~override~
  PATCH_IF (VARIABLE_IS_SET %spellshield_sectype%) BEGIN
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 221 parameter2 = %spellshield_sectype% END
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 parameter2 = %spellshield_sectype% END
  END


// secret word

COPY ~%MOD_FOLDER%/data/spl/spwi419.spl~ ~override~
//  SAY NAME1 @124191
  SAY UNIDENTIFIED_DESC @12419
  READ_SHORT 0x1c spl_typ
  PATCH_IF (FILE_EXISTS_IN_GAME ~d5__psionics.d5~) BEGIN
    PATCH_IF (spl_typ = 1) BEGIN
      LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5psaura~ END
    END
  END
  PATCH_IF (MOD_IS_INSTALLED ~stratagems.tp2~ ~6000~) BEGIN	// or (FILE_EXISTS_IN_GAME ~DW#BLHDA.spl~)
    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = ~DW#HDANI~ END
    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 146 target = 1 parameter1 = 1 parameter2 = 1 timing = 0 STR_VAR resource = ~DW#BLHDA~ END
  END
  
COPY ~%MOD_FOLDER%/data/spl/spwi419b.spl~ ~override~
  PATCH_IF (attack_delay > 0) BEGIN
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 timing = 4 duration = %attack_delay% END
  END

COPY ~%MOD_FOLDER%/data/spl/spwi419c.spl~ ~override~
  PATCH_IF (VARIABLE_IS_SET %spellshield_sectype%) BEGIN
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 221 parameter2 = %spellshield_sectype% END
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 parameter2 = %spellshield_sectype% END
  END
  

// pierce magic

COPY ~%MOD_FOLDER%/data/spl/spwi608.spl~ ~override~
//  SAY NAME1 @126081
  SAY UNIDENTIFIED_DESC @12608
  READ_SHORT 0x1c spl_typ
  PATCH_IF (FILE_EXISTS_IN_GAME ~d5__psionics.d5~) BEGIN
    PATCH_IF (spl_typ = 1) BEGIN
      LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5psaura~ END
    END
  END
  PATCH_IF (MOD_IS_INSTALLED ~stratagems.tp2~ ~6000~) BEGIN	// or (FILE_EXISTS_IN_GAME ~DW#BLHDA.spl~)
    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = ~DW#HDANI~ END
    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 146 target = 1 parameter1 = 1 parameter2 = 1 timing = 0 STR_VAR resource = ~DW#BLHDA~ END
  END
  
COPY ~%MOD_FOLDER%/data/spl/spwi608b.spl~ ~override~
  PATCH_IF (attack_delay > 0) BEGIN
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 timing = 4 duration = %attack_delay% END
  END

COPY ~%MOD_FOLDER%/data/spl/spwi608c.spl~ ~override~
  PATCH_IF (VARIABLE_IS_SET %spellshield_sectype%) BEGIN
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 221 parameter2 = %spellshield_sectype% END
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 parameter2 = %spellshield_sectype% END
  END


// ruby ray

COPY ~%MOD_FOLDER%/data/spl/spwi704.spl~ ~override~
//  SAY NAME1 @127041
  SAY UNIDENTIFIED_DESC @12704
  READ_SHORT 0x1c spl_typ
  PATCH_IF (FILE_EXISTS_IN_GAME ~d5__psionics.d5~) BEGIN
    PATCH_IF (spl_typ = 1) BEGIN
      LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5psaura~ END
    END
  END
  PATCH_IF (MOD_IS_INSTALLED ~stratagems.tp2~ ~6000~) BEGIN	// or (FILE_EXISTS_IN_GAME ~DW#BLHDA.spl~)
    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = ~DW#HDANI~ END
    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 146 target = 1 parameter1 = 1 parameter2 = 1 timing = 0 STR_VAR resource = ~DW#BLHDA~ END
  END
  
COPY ~%MOD_FOLDER%/data/spl/spwi704b.spl~ ~override~
  PATCH_IF (attack_delay > 0) BEGIN
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 timing = 4 duration = %attack_delay% END
  END

COPY ~%MOD_FOLDER%/data/spl/spwi704c.spl~ ~override~
  PATCH_IF (VARIABLE_IS_SET %spellshield_sectype%) BEGIN
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 221 parameter2 = %spellshield_sectype% END
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 parameter2 = %spellshield_sectype% END
  END


// warding whip

COPY ~%MOD_FOLDER%/data/spl/spwi705.spl~ ~override~
//  SAY NAME1 @127051
  SAY UNIDENTIFIED_DESC @12705
  READ_SHORT 0x1c spl_typ
  PATCH_IF (FILE_EXISTS_IN_GAME ~d5__psionics.d5~) BEGIN
    PATCH_IF (spl_typ = 1) BEGIN
      LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5psaura~ END
    END
  END
  PATCH_IF (MOD_IS_INSTALLED ~stratagems.tp2~ ~6000~) BEGIN	// or (FILE_EXISTS_IN_GAME ~DW#BLHDA.spl~)
    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = ~DW#HDANI~ END
    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 146 target = 1 parameter1 = 1 parameter2 = 1 timing = 0 STR_VAR resource = ~DW#BLHDA~ END
  END
  
COPY ~%MOD_FOLDER%/data/spl/spwi705b.spl~ ~override~
  PATCH_IF (attack_delay > 0) BEGIN
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 timing = 4 duration = %attack_delay% END
  END

COPY ~%MOD_FOLDER%/data/spl/spwi705c.spl~ ~override~
  PATCH_IF (VARIABLE_IS_SET %spellshield_sectype%) BEGIN
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 221 parameter2 = %spellshield_sectype% END
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 parameter2 = %spellshield_sectype% END
  END


// pierce shield

COPY ~%MOD_FOLDER%/data/spl/spwi805.spl~ ~override~
//  SAY NAME1 @128051
  SAY UNIDENTIFIED_DESC @12805
  READ_SHORT 0x1c spl_typ
  PATCH_IF (FILE_EXISTS_IN_GAME ~d5__bards.d5~) BEGIN
    WRITE_BYTE 0x1f (THIS BOR 0b10000000)
    WRITE_BYTE 0x20 (THIS BOR 0b10000010)
  END
  PATCH_IF (FILE_EXISTS_IN_GAME ~d5__psionics.d5~) BEGIN
    PATCH_IF (spl_typ = 1) BEGIN
      LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5psaura~ END
    END
  END
  PATCH_IF (MOD_IS_INSTALLED ~stratagems.tp2~ ~6000~) BEGIN	// or (FILE_EXISTS_IN_GAME ~DW#BLHDA.spl~)
    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = ~DW#HDANI~ END
    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 146 target = 1 parameter1 = 1 parameter2 = 1 timing = 0 STR_VAR resource = ~DW#BLHDA~ END
  END
  
COPY ~%MOD_FOLDER%/data/spl/spwi805b.spl~ ~override~
  PATCH_IF (attack_delay > 0) BEGIN
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 timing = 4 duration = %attack_delay% END
  END

COPY ~%MOD_FOLDER%/data/spl/spwi805c.spl~ ~override~
  PATCH_IF (VARIABLE_IS_SET %spellshield_sectype%) BEGIN
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 221 parameter2 = %spellshield_sectype% END
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 parameter2 = %spellshield_sectype% END
  END


// spellstrike

COPY ~%MOD_FOLDER%/data/spl/spwi903.spl~ ~override~
//  SAY NAME1 @129031
  SAY UNIDENTIFIED_DESC @12903
  READ_SHORT 0x1c spl_typ
  PATCH_IF (FILE_EXISTS_IN_GAME ~d5__bards.d5~) BEGIN
    WRITE_BYTE 0x1f (THIS BOR 0b10000000)
    WRITE_BYTE 0x20 (THIS BOR 0b10000010)
  END
  PATCH_IF (FILE_EXISTS_IN_GAME ~d5__psionics.d5~) BEGIN
    PATCH_IF (spl_typ = 1) BEGIN
      LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5psaura~ END
    END
  END
  PATCH_IF (MOD_IS_INSTALLED ~stratagems.tp2~ ~6000~) BEGIN	// or (FILE_EXISTS_IN_GAME ~DW#BLHDA.spl~)
    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = ~DW#HDANI~ END
    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 146 target = 1 parameter1 = 1 parameter2 = 1 timing = 0 STR_VAR resource = ~DW#BLHDA~ END
  END
  
COPY ~%MOD_FOLDER%/data/spl/spwi903b.spl~ ~override~
  PATCH_IF (attack_delay > 0) BEGIN
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 timing = 4 duration = %attack_delay% END
  END

COPY ~%MOD_FOLDER%/data/spl/spwi903c.spl~ ~override~
  PATCH_IF (VARIABLE_IS_SET %spellshield_sectype%) BEGIN
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 221 parameter2 = %spellshield_sectype% END
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 parameter2 = %spellshield_sectype% END
  END


// also, change spell thrust to a different level

ACTION_IF (st_lvl != 3) AND (st_lvl > 0) AND (st_lvl < 10) BEGIN

  OUTER_SET st_known_level = (st_lvl - 1)
  
  OUTER_SPRINT stkl ~#%st_known_level%~

// this might be installed late, so need to check for L1Cantrips, and add the op261 stuff here

  COPY_EXISTING ~spwi321.spl~ ~override~
  ADD_SPELL ~override/spwi321.spl~ 2 %st_lvl% WIZARD_SPELL_THRUST
    SAY NAME1 @123211
	SAY UNIDENTIFIED_DESC @12321
	WRITE_LONG 0x34 1
  LAF RES_NUM_OF_SPELL_NAME
	STR_VAR spell_name = ~WIZARD_SPELL_THRUST~
	RET spell_res
  END
  ACTION_IF FILE_EXISTS_IN_GAME ~scrl6j.itm~ THEN BEGIN
	COPY_EXISTING ~scrl6j.itm~ ~override~
	  SAY IDENTIFIED_DESC @12321
	  WRITE_LONG 0x34 100
	  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = EVAL ~%spell_res%~ END
	  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 147 STR_VAR resource = EVAL ~%spell_res%~ END					
	  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 148 STR_VAR resource = EVAL ~%spell_res%~ END
  END
  COPY_EXISTING_REGEXP GLOB ~^.+\.cre$~ ~override~
	PATCH_IF (%SOURCE_SIZE% > 0x2d3) BEGIN
	  READ_BYTE 0x273 class
	  PATCH_IF (class == 1 || class == 13 || class == 14 || class == 7 || class == 10 || class == 17 || class == 19 || class == 5) BEGIN // wizard casters
		ADD_KNOWN_SPELL ~%spell_res%~ (st_known_level) ~wizard~
		ADD_MEMORIZED_SPELL ~%spell_res%~ (st_known_level) ~wizard~
	  END
	END
  BUT_ONLY
  ACTION_IF (GAME_IS ~bgee bg2ee eet~) BEGIN
	APPEND ~hidespl.2da~ ~spwi321	1		0		0 ~
  END
  ACTION_IF (GAME_IS ~iwdee~) BEGIN
	APPEND ~hidespl.2da~ ~spwi321	1		0 ~
  END
  
  ACTION_IF (st_lvl = 1) BEGIN
    ACTION_IF (FILE_EXISTS_IN_GAME ~qdtnb_l1cantrips.qd~) BEGIN
      COPY_EXISTING ~%spell_res%.spl~ ~override~
        LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 144 parameter2 = 5 timing = 0 duration = 1  END
        LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 144 parameter2 = 4 timing = 0 duration = 1  END
        LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 144 parameter2 = 3 timing = 0 duration = 1  END
        LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 144 parameter2 = 2 timing = 0 duration = 1  END
        LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 261 parameter1 = 1 timing = 1 duration = 0  END
      BUT_ONLY
    END  
  END

  ACTION_IF (FILE_EXISTS_IN_GAME ~dvsplthr.pro~) BEGIN
	COPY_EXISTING ~dvsplthr.pro~ ~override~
	  WRITE_SHORT 0x204 65
	  WRITE_SHORT 0x206 65
	BUT_ONLY
  END

  ACTION_IF (FILE_EXISTS_IN_GAME ~d5__5E_casting_arcane.d5~) BEGIN
    COPY_EXISTING ~d5zclons.2da~ ~override~
      COUNT_2DA_ROWS 5 rows
      FOR (row  = 1;row <rows; ++row) BEGIN
        READ_2DA_ENTRY row 2 5 splth
        PATCH_IF (~%splth%~ STRING_EQUAL_CASE ~spwi321~) BEGIN
          READ_2DA_ENTRY row 0 5 zind
        END
      END    
    IF_EXISTS BUT_ONLY
  END
/*  why bother?
  ACTION_IF (VARIABLE_IS_SET %zind%) BEGIN
    COPY_EXISTING ~d5z%zind%i.spl~ ~override~
      LPF ALTER_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = ~spwi321~ resource = EVAL ~%spell_res%~ END
      LPF ALTER_EFFECT INT_VAR match_opcode = 148 STR_VAR match_resource = ~spwi321~ resource = EVAL ~%spell_res%~ END
    IF_EXISTS BUT_ONLY
  END
*/
  OUTER_SET lose_spell_on_interrupt = 0
  ACTION_IF (FILE_EXISTS_IN_GAME ~d5d5zlotr.bcs~) BEGIN
    COPY_EXISTING ~d5d5zlotr.bcs~ ~override~
      DECOMPILE_AND_PATCH BEGIN
        REPLACE_TEXTUALLY ~spwi321~ ~%spell_res%~
      END
    BUT_ONLY
  END
  ACTION_IF (FILE_EXISTS_IN_GAME ~d5xsorc.itm~) BEGIN
    INCLUDE ~%MOD_FOLDER%/lib/semi_spontaneous.tpa~
    APPEND ~d5xsorc.2da~ ~sorcerer	%spell_res%	3~
    COPY_EXISTING ~%spell_res%.spl~ ~override~
      READ_ASCII 0x3a spell_icon
    BUT_ONLY
    COPY_EXISTING ~%MOD_FOLDER%/data/d5_base.spl~ ~override/%spell_res%w.spl~
      SAY NAME1 @123211
      SAY UNIDENTIFIED_DESC @12321
	  WRITE_EVALUATED_ASCII 0x3a ~%spell_icon%~ #8
	  LPF ALTER_SPELL_HEADER STR_VAR icon = EVAL ~%spell_icon%~ END
  	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = ~%spell_res%~ END
  	COPY_EXISTING ~d5xclons.2da~ ~override~
  	  REPLACE_TEXTUALLY ~SPWI321~ ~%spell_res%~
  	IF_EXISTS BUT_ONLY
  	COPY_EXISTING ~d5xclons.2da~ ~override~
      COUNT_2DA_ROWS 5 rows
      FOR (row  = 1;row <rows; ++row) BEGIN
        READ_2DA_ENTRY row 1 5 spl
        PATCH_IF (~%spl%~ STRING_EQUAL_CASE ~%spell_res%~) BEGIN
          SET_2DA_ENTRY row 4 5 no
        END
      END
  	IF_EXISTS BUT_ONLY      
    LAF semi_sorcerer_casting END
  END
  
END


//__________________________________________________________________________________
//__________________________________________________________________________________


// - buff attacks


// Breach:


ACTION_FOR_EACH br_spl IN ~spwi513~ ~dfp2513~ ~d5f2513~ ~d5_rabre~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%br_spl%.spl~) BEGIN
    COPY ~%MOD_FOLDER%/data/spl/%br_spl%.spl~ ~override~
      SAY NAME1 @125131
      SAY UNIDENTIFIED_DESC @12513
	  READ_SHORT 0x1c spl_typ
	  PATCH_IF (VARIABLE_IS_SET %breach_sectype%) BEGIN
	    WRITE_BYTE 0x27 %breach_sectype%
	  END
	  ELSE BEGIN
	    WRITE_BYTE 0x27 0
	  END
      PATCH_IF (FILE_EXISTS_IN_GAME ~spwi513c.spl~) BEGIN
        LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 146 STR_VAR insert = ~last~ resource = ~spwi513c~ END
      END
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5__psionics.d5~) BEGIN
	    PATCH_IF (spl_typ = 1) BEGIN
	      LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5psaura~ END
	    END
	  END
	  PATCH_IF (MOD_IS_INSTALLED ~stratagems.tp2~ ~6000~) BEGIN	// or (FILE_EXISTS_IN_GAME ~DW#BLHDA.spl~)
	    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = ~DW#HDANI~ END
	    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 146 target = 1 parameter1 = 1 parameter2 = 1 timing = 0 STR_VAR resource = ~DW#BLHDA~ END
	  END
  END
END

COPY ~%MOD_FOLDER%/data/spl/spwi513b.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 221 parameter1 = 10 END
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 parameter1 = 10 END
	PATCH_IF breach_combat = 0 BEGIN
	  LPF DELETE_EFFECT INT_VAR match_opcode = 221 match_parameter2 = 7 END
	END
	PATCH_IF breach_spec = 0 BEGIN
	  LPF DELETE_EFFECT INT_VAR match_opcode = 221 match_parameter2 = 2 END
	END
	PATCH_IF breach_combi = 1 BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 221 target = 2 power = 5 parameter1 = 9 parameter2 = 12 timing = 1 END
	END
	PATCH_IF breach_noncomb = 1 BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 221 target = 2 power = 5 parameter1 = 9 parameter2 = 13 timing = 1 END
	END

ACTION_IF (FILE_EXISTS_IN_GAME ~spwi513c.spl~) BEGIN
  COPY ~%MOD_FOLDER%/data/spl/spwi513c.spl~ ~override~
    SAY NAME1 ~~
    SAY UNIDENTIFIED_DESC ~~
    PATCH_IF (VARIABLE_IS_SET %k1_dispel_sectype%) BEGIN
      LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 221 parameter2 = %k1_dispel_sectype% END
      LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 parameter2 = %k1_dispel_sectype% END
    END
END

COPY_EXISTING ~rakring.itm~ ~override~
// add level 5 spell immunity
  LPF DELETE_EFFECT INT_VAR match_opcode = 102 match_parameter1 = 5 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 102 match_parameter1 = 4 parameter1 = 5 END
IF_EXISTS BUT_ONLY

COPY_EXISTING ~lich.itm~ ~override~
  LPF DELETE_EFFECT INT_VAR match_opcode = 102 match_parameter1 = 5 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 102 match_parameter1 = 4 parameter1 = 5 END
IF_EXISTS BUT_ONLY

COPY_EXISTING ~dw#licim.spl~ ~override~
  LPF DELETE_EFFECT INT_VAR match_opcode = 102 match_parameter1 = 5 END
  LPF CLONE_EFFECT INT_VAR match_opcode = 102 match_parameter1 = 4 parameter1 = 5 END
IF_EXISTS BUT_ONLY

// patch entropy shield to block spwi513b instead of spwi513:
// 
ACTION_IF (FILE_EXISTS_IN_GAME ~spwi513b.spl~) BEGIN
  OUTER_SET entropy_shield_num = IDS_OF_SYMBOL (~spell~ ~CLERIC_ENTROPY_SHIELD~)
  ACTION_IF (entropy_shield_num > 0) BEGIN
    LAF RES_NUM_OF_SPELL_NAME
	  STR_VAR spell_name = ~CLERIC_ENTROPY_SHIELD~
	  RET spell_res
    END
    ACTION_IF (FILE_EXISTS_IN_GAME ~%spell_res%.spl~) BEGIN
      COPY_EXISTING ~%spell_res%.spl~ ~override~
// ...change to k1#dispel sectype?
        PATCH_IF (FILE_EXISTS_IN_GAME ~k1#scre.spl~) AND (VARIABLE_IS_SET %k1_dispel_sectype%) BEGIN
          WRITE_BYTE 0x27 %k1_dispel_sectype%
        END
        LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 206 STR_VAR match_resource = ~spwi513~ resource = ~spwi513b~ END
        LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 318 STR_VAR match_resource = ~spwi513~ resource = ~spwi513b~ END
        LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 324 STR_VAR match_resource = ~spwi513~ resource = ~spwi513b~ END
      BUT_ONLY
    END
  END
END

// Remove Magic  

COPY ~%MOD_FOLDER%/data/spl/d5disrem.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 221 parameter1 = 10 END
  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 230 parameter1 = 10 END

ACTION_IF !(FILE_EXISTS_IN_GAME ~a^dispe2.spl~) BEGIN
 ACTION_FOR_EACH rm_spl IN ~spwi302~ ~rr#wi302~ ~ohbwi302~ ~staf11a~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%rm_spl%.spl~) BEGIN
    COPY ~%MOD_FOLDER%/data/spl/%rm_spl%.spl~ ~override~
      SAY NAME1 @123021
      SAY UNIDENTIFIED_DESC @12302
	  READ_SHORT 0x1c spl_typ
      PATCH_IF (breachy_remove = 0) BEGIN
        LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR match_resource = ~d5disrem~ resource = ~d5dispel~ END
        WRITE_LONG 0x50 %og_rm_desc_string%
      END      
      PATCH_IF (FILE_EXISTS_IN_GAME ~spwi513c.spl~) BEGIN
        LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 146 STR_VAR insert = ~last~ resource = ~spwi513c~ END
      END
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5__psionics.d5~) BEGIN
	    PATCH_IF (spl_typ = 1) BEGIN
	      LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5psaura~ END
	    END
	  END
	  PATCH_IF (MOD_IS_INSTALLED ~stratagems.tp2~ ~6000~) BEGIN	// or (FILE_EXISTS_IN_GAME ~DW#BLHDA.spl~)
	    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = ~DW#HDANI~ END
	    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 146 target = 1 parameter1 = 1 parameter2 = 1 timing = 0 STR_VAR resource = ~DW#BLHDA~ END
	  END
  END
 END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~a^dispe2.spl~) BEGIN
 ACTION_FOR_EACH rm_spl IN ~spwi302~ ~rr#wi302~ ~ohbwi302~ ~staf11a~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%rm_spl%.spl~) BEGIN
    ACTION_IF (breachy_remove = 1) BEGIN
      COPY ~%MOD_FOLDER%/data/spl/%rm_spl%.spl~ ~override~
        SAY NAME1 @123021
        SAY UNIDENTIFIED_DESC @12302
        LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR match_resource = ~a^dispe2~ resource = ~d5disrem~ END
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5__psionics.d5~) BEGIN
	      PATCH_IF (spl_typ = 1) BEGIN
	        LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5psaura~ END
	      END
	    END
	    PATCH_IF (MOD_IS_INSTALLED ~stratagems.tp2~ ~6000~) BEGIN	// or (FILE_EXISTS_IN_GAME ~DW#BLHDA.spl~)
	      LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = ~DW#HDANI~ END
	      LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 146 target = 1 parameter1 = 1 parameter2 = 1 timing = 0 STR_VAR resource = ~DW#BLHDA~ END
	    END
    END
    ACTION_IF (breachy_remove = 0) BEGIN
      COPY_EXISTING ~%rm_spl%.spl~ ~override~
        LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR match_resource = ~a^dispe2~ resource = ~d5dispel~ END
    END
  END
 END
END


// Dispel Magic  

COPY_EXISTING - ~spwi302.spl~ ~override~
  READ_LONG 0x50 og_rm_desc_string
COPY_EXISTING - ~spwi326.spl~ ~override~
  READ_LONG 0x50 og_dm_desc_string

ACTION_IF !(FILE_EXISTS_IN_GAME ~a^dispe2.spl~) BEGIN
 ACTION_FOR_EACH dm_spl IN ~spwi326~ ~sppr303~ ~rr#wi326~ ~spcl231~ ~spin112~ ~spin703~ ~spin866~ ~sw2h10dm~ ~tg#rc08~ ~tg#rc42~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%dm_spl%.spl~) BEGIN
    COPY ~%MOD_FOLDER%/data/spl/%dm_spl%.spl~ ~override~
	  READ_SHORT 0x1c spl_typ
      PATCH_IF (friendly_dispel = 0) BEGIN
        PATCH_IF (breachy_dispel = 0) BEGIN
          WRITE_LONG 0x50 %og_dm_desc_string%
        END      
        PATCH_IF (breachy_dispel = 1) BEGIN
          LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR match_resource = ~d5dispel~ resource = ~d5disrem~ END
          SAY UNIDENTIFIED_DESC @12326
        END      
      END
      PATCH_IF (friendly_dispel = 1) BEGIN
        LPF ALTER_SPELL_HEADER INT_VAR projectile = 177 END
        PATCH_IF (breachy_dispel = 0) BEGIN
          WRITE_LONG 0x50 %og_rm_desc_string%
        END      
        PATCH_IF (breachy_dispel = 1) BEGIN
          LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR match_resource = ~d5dispel~ resource = ~d5disrem~ END
          SAY UNIDENTIFIED_DESC @12302
        END      
      END
      PATCH_IF (FILE_EXISTS_IN_GAME ~spwi513c.spl~) BEGIN
        LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 146 STR_VAR insert = ~last~ resource = ~spwi513c~ END
      END
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5__psionics.d5~) BEGIN
	    PATCH_IF (spl_typ = 1) BEGIN
	      LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5psaura~ END
	    END
	  END
	  PATCH_IF (MOD_IS_INSTALLED ~stratagems.tp2~ ~6000~) BEGIN	// or (FILE_EXISTS_IN_GAME ~DW#BLHDA.spl~)
	    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 321 target = 1 parameter1 = 0 parameter2 = 0 timing = 0 STR_VAR resource = ~DW#HDANI~ END
	    LPF ADD_SPELL_CFEFFECT INT_VAR opcode = 146 target = 1 parameter1 = 1 parameter2 = 1 timing = 0 STR_VAR resource = ~DW#BLHDA~ END
	  END
  END
 END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~a^dispe2.spl~) BEGIN
 ACTION_FOR_EACH dm_spl IN ~spwi326~ ~sppr303~ ~rr#wi326~ ~spcl231~ ~spin112~ ~spin703~ ~spin866~ ~sw2h10dm~ ~tg#rc08~ ~tg#rc42~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%dm_spl%.spl~) BEGIN
    COPY_EXISTING ~%dm_spl%.spl~ ~override~
      PATCH_IF (friendly_dispel = 1) BEGIN
        LPF ALTER_SPELL_HEADER INT_VAR projectile = 177 END
        PATCH_IF (breachy_dispel = 0) BEGIN
          LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR match_resource = ~a^dispe2~ resource = ~d5dispel~ END
          WRITE_LONG 0x50 %og_rm_desc_string%
        END      
        PATCH_IF (breachy_dispel = 1) BEGIN
          LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR match_resource = ~a^dispe2~ resource = ~d5disrem~ END
          SAY UNIDENTIFIED_DESC @12302
        END      
      END
      PATCH_IF (friendly_dispel = 0) BEGIN
        PATCH_IF (breachy_dispel = 0) BEGIN
          LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR match_resource = ~a^dispe2~ resource = ~d5dispel~ END
          WRITE_LONG 0x50 %og_dm_desc_string%
        END      
        PATCH_IF (breachy_dispel = 1) BEGIN
          LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR match_resource = ~a^dispe2~ resource = ~d5disrem~ END
          SAY UNIDENTIFIED_DESC @12326
        END      
      END
      PATCH_IF (FILE_EXISTS_IN_GAME ~spwi513c.spl~) BEGIN
        LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = ~spwi513c~ END
        LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 146 STR_VAR insert = ~last~ resource = ~spwi513c~ END
      END
  END
 END      
END


// ///////////////////////////////////////////////////////////////////////////////////


END		//	end define function

